service: docker-serverless-study

provider:
  name: aws
  runtime: ruby2.7
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    logLevel: debug